### ISSUE TITLE
no emoji support

### ISSUE THREAD

**Issue by gabrielcsapo** [lmarkus/openBadge#2]
```
openBadge({
            text: ['emoji-test', '🗿'],
            font: {
                fontFace: '../../fonts/NotoColorEmoji.ttf'
            }
        }, function(err, badgeSvg) {
            res.set('Content-Type', 'image/svg+xml');
            res.send(badgeSvg);
        });
```

this renders 

<img width="110" alt="screen shot 2016-06-18 at 5 59 59 pm" src="https://cloud.githubusercontent.com/assets/1854811/16174616/8a8ab83c-357e-11e6-910b-1d05b0794fb2.png">

This looks like it is a problem with the `opentype.js` module, a replacement that supports colored glyphs is (https://github.com/devongovett/fontkit)

**Comment by lmarkus** [comment]
PRs welcome :)
